### ISSUE TITLE
 Could not get unknown property 'idea' for root project

### ISSUE THREAD

**Issue by throll** [palantir/gradle-processors#53]
Hi,

I cannot make this plugin work on my project, i always get the same error during build : 
` Could not get unknown property 'idea' for root project`

Any thoughts ?

**Comment by chrisalice** [comment]
Can you run with --stacktrace and post the full output? Also, what command are you running?

**Comment by throll** [comment]
Hi and thanks to take care of my problem, i'm just running a build after adding plugin in my build.gradle : 

`./gradlew clean build --stacktrace`

`org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.inferred.processors', version: '1.2.5']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:224)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:171)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'org.inferred.processors']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:174)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:212)
        ... 61 more
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'idea' for root project 'XXX' of type org.gradle.api.Project.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
        at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11$_closure35$_closure36.doCall(ProcessorsPlugin.groovy:209)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11$_closure35$_closure36.doCall(ProcessorsPlugin.groovy)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11$_closure35.doCall(ProcessorsPlugin.groovy:208)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11$_closure35.doCall(ProcessorsPlugin.groovy)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11.doCall(ProcessorsPlugin.groovy:207)
        at org.inferred.gradle.ProcessorsPlugin$_updateIdeaCompilerConfiguration_closure11.doCall(ProcessorsPlugin.groovy)
        at org.inferred.gradle.ProcessorsPlugin.updateIdeaCompilerConfiguration(ProcessorsPlugin.groovy:206)
        at org.inferred.gradle.ProcessorsPlugin$updateIdeaCompilerConfiguration.callStatic(Unknown Source)
        at org.inferred.gradle.ProcessorsPlugin.apply(ProcessorsPlugin.groovy:118)
        at org.inferred.gradle.ProcessorsPlugin.apply(ProcessorsPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 64 more

`

**Comment by chrisalice** [comment]
Looks like we assume that, if the file ".idea/compiler.xml" exists, that your root project is applying the 'idea' plugin. As a quick workaround, I suggest you add `apply plugin: 'idea'` to your root project.

**Comment by throll** [comment]
idea plugin is already there : 
`plugins {
    id 'idea'
    id 'com.github.ben-manes.versions' version '0.13.0'
    id 'java'
    id "org.inferred.processors" version "1.2.5"
    id 'jacoco'
}`

**Comment by chrisalice** [comment]
Thanks for that update! Seems this is caused by the order Gradle is applying the plugins. I've got a failing test and I'll put a fix together; meantime, as a workaround you can try permuting the order you declare your plugins 😞

**Comment by Silberling** [comment]
Same problem here. Played around with the order of the plugins, didn't help.

**Comment by Silberling** [comment]
1.2.6 is working. Thanks so much for the quick update. Awesome.

**Comment by chrisalice** [comment]
Wonderful! You're most welcome :)

**Comment by Silberling** [comment]
May I ask you something?

Everything is working on my "Processor development project", but when Integrating it into the main project I have issues, like the one you solved. But now I have trouble integrating it into a selection of subprojects.  For example:

    plugins {
        id "org.inferred.processors" version "1.2.6"
    }

    repositories {
        mavenCentral()
    }

    project(':A') {
        // ...
    }

    project(':B') {
        // ...
    }

    project(':C') {
        // ...
    }

    project(':D') {
        // ...
    }

    configure([project(':B'), project(':C'), project(':D')]) {
        apply plugin: 'java'
        apply plugin: 'idea'
        // ...
    }

    configure([project(':B'), project(':C')]) {
       // ...
       
       dependencies {
           // ...
           processor files('../../CustomProcessor/build/libs/CustomProcessor.jar')
       }
    }

There are multiple subprojects, but only B and C need to use the CustomProcessor.

But I get

    Could not find method processor() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

or again:

    Could not get unknown property 'idea' for root project 'Main' of type org.gradle.api.Project.

When trying to apply the plugin only in one subproject.

I am fairly new to gradle and this is a real struggle, so I'd love to get a hint.

**Comment by chrisalice** [comment]
You need to apply the gradle-processors plugin to your subprojects, not the top-level project.

I would recommend configuring your subprojects in a separate file, e.g. A/build.gradle, B/build.gradle, rather than having one huge top-level file like this. You can pull those files in in your `settings.gradle`:

```
include "A"
include "B"
```

**Comment by Silberling** [comment]
MMh okay, as far as I understood https://docs.gradle.org/current/userguide/plugins.html I did this

	plugins {
		id "org.inferred.processors" version "1.2.6" apply false
	}

	// ...

	configure([project(':B'), project(':C')]) {
		apply plugin: "org.inferred.processors"
		
		// ...

		dependencies {
			// ...
			processor files('../../CustomProcessor/build/libs/CustomProcessor.jar')
		}
	}

to not apply it to the top-level project but to the subprojects. And I tried to apply it only to one single subproject in the project() part.
But I get

	Could not get unknown property 'idea' for root project 'Main' of type org.gradle.api.Project.

I'm afraid I can't split the gradle.build file right now, but I keep it in mind.

**Comment by chrisalice** [comment]
Could you run with `--stacktrace` and post the output? Also, what's the exact command you're running?

**Comment by Silberling** [comment]
gradlew build / gradlew clean, mostly clean because thats the first one I normally run when using the command line.

	> gradlew clean --stacktrace

	FAILURE: Build failed with an exception.

	* Where:
	Build file 'C:\Users\User\Projects\Main\build.gradle' line: 157

	* What went wrong:
	A problem occurred evaluating root project 'Main'.
	> Failed to apply plugin [id 'org.inferred.processors']
	   > Could not get unknown property 'idea' for root project 'Main' of type org.gradle.api.Project.

	* Try:
	Run with --info or --debug option to get more log output.

	* Exception is:
	org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'Main'.
	        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
	        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
	        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
	        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
	        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
	        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
	        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
	        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
	        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
	        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	        at org.gradle.util.Swapper.swap(Swapper.java:38)
	        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'org.inferred.processors']
	        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
	        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
	        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
	        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
	        at build_bo1re6gdrd2orhnm3olejcj67$_run_closure8.doCall(C:\Users\User\Projects\Main\build.gradle:157)
	        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	        at org.gradle.api.internal.project.DefaultProject.project(DefaultProject.java:979)
	        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
	        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
	        at build_bo1re6gdrd2orhnm3olejcj67.run(C:\Users\User\Projects\Main\build.gradle:155)
	        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	        ... 62 more
	Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'idea' for root project 'Main' of type org.gradle.api.Project.
	        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
	        at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
	        at org.inferred.gradle.ProcessorsPlugin$_apply_closure3$_closure25.doCall(ProcessorsPlugin.groovy:104)
	        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:122)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:133)
	        at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
	        at org.inferred.gradle.ProcessorsPlugin$_apply_closure3.doCall(ProcessorsPlugin.groovy:89)
	        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:122)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:133)
	        at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
	        at org.inferred.gradle.ProcessorsPlugin.apply(ProcessorsPlugin.groovy:88)
	        at org.inferred.gradle.ProcessorsPlugin.apply(ProcessorsPlugin.groovy)
	        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
	        ... 86 more


	BUILD FAILED

	Total time: 1.19 secs

**Comment by chrisalice** [comment]
I see the bug. As a workaround, could you try applying the idea plugin to your root project? I won't be able to work on this until tomorrow, unfortunately.

**Comment by Silberling** [comment]
That's perfectly fine ;-) I can work on other parts in the mean time.

**Comment by chrisalice** [comment]
Could you give 1.2.7 a whirl?

**Comment by Silberling** [comment]
Just did, responded in the other issue. Works perfectly. Thank you very much for your help ;-)

**Comment by alaphavr** [comment]
so ya im haveing the same proplem im on win 11 and im useing vs code and im stuck

**Comment by alaphavr** [comment]
o dang i just reail ised how long ago this was

**Comment by alaphavr** [comment]
o and btw its with a mod
